# Generated by Django 5.2.6 on 2025-10-12 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=100)),
                ('year_of_manufacture', models.DateField()),
                ('daily_rental_price', models.FloatField(default=0.0)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='car_photos/')),
                ('available_dates', models.JSONField(blank=True, null=True)),
                ('rental_terms', models.TextField(blank=True, null=True)),
                ('deposit', models.FloatField(default=0.0)),
                ('deposit_percentage', models.FloatField(default=0.0)),
                ('is_available', models.BooleanField(default=True)),
                ('license', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
