# Generated by Django 5.2.6 on 2025-10-13 14:34

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_photos_carphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(validators=[cars.models.validate_year]),
        ),
    ]
