# Generated by Django 5.2.6 on 2025-11-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_color_car_duration_non_paid_in_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(default='XXXXXX', editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
