# Generated by Django 5.2.6 on 2025-11-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_reservation_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='is_paid',
            new_name='deposit_paid',
        ),
        migrations.RemoveField(
            model_name='car',
            name='available_dates',
        ),
        migrations.AddField(
            model_name='reservation',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='balance_due',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='car',
            name='deposit',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
