# Generated by Django 5.2.6 on 2025-11-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_is_paid_reservation_deposit_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='deposit',
        ),
    ]
