# Generated by Django 5.2.6 on 2025-11-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='deposit_paid',
            new_name='has_paid_deposit',
        ),
    ]
