# Generated by Django 5.2.6 on 2025-11-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_deposit_paid_reservation_has_paid_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='new_daily_rental_price',
            field=models.FloatField(default=0.0),
        ),
    ]
