# Generated by Django 5.2.6 on 2025-11-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_reservation_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancel_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
