# Generated by Django 5.2.6 on 2025-11-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_reservation_cancel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
