# Generated by Django 5.2.6 on 2025-11-12 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_reservation_is_paid'),
        ('payments', '0002_remove_payment_user_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cars.reservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='initialized', max_length=20),
        ),
    ]
