# Generated by Django 5.2.6 on 2025-11-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_reservation_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='authorization_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
