# Generated by Django 5.2.6 on 2025-11-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
