# Generated by Django 5.2.6 on 2025-10-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
