# Generated by Django 5.2.6 on 2025-10-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='expiry_date',
            new_name='license_expiry_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='issue_date',
            new_name='license_issue_date',
        ),
    ]
