# Generated by Django 5.2.6 on 2025-10-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_expiry_date_profile_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='back_image',
            new_name='license_back_image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='front_image',
            new_name='license_front_image',
        ),
    ]
