# Generated by Django 5.2.6 on 2025-10-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_back_image_profile_license_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country_or_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
